import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Toaster } from "react-hot-toast";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "TuTi CARGO",
  description: "Generated by addiis co",
  icons: "/tuti-logo.png",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="">
      <body className={`${inter.className} antialiased bg-[#eee]`}>
        <Toaster position="top-center"/>
        {children}
      </body>
    </html>
  );
}
